# Site settings
title: Design, Build, Test, Repeat
email: mkivikoski@cantina.co
description: > # this means to ignore newlines until "baseurl:"
  Design, Build, Test, Repeat is a podcast for and about User Interface Design and Development for web applications. Hosted by Eric Bailey and Mike Kivikoski   
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dbtrpodcast
github_username: 

# Build settings
markdown: kramdown
